spring.application.name=GROUP1_SPRING_MINI_PROJECT001

spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}

# MyBatis
mybatis.type-handlers-package=com.rith.group1_spring_mini_project001.util

# RustFS
rustfs.url=${RUSTFS_URL}
rustfs.access.name=${RUSTFS_ACCESS_NAME}
rustfs.access.secret=${RUSTFS_ACCESS_SECRET}
rustfs.bucket.name=file-upload

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true