spring.application.name=GROUP1_SPRING_MINI_PROJECT001
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_mini
spring.datasource.username=postgres
spring.datasource.password=admin123

jwt.secret=FVPr6Q/fVlHGZkElZubC0Zaxv657dPUfDQ4o9DADjSin7+uST1d2A5klMWrMK8fmSl3doyf2wn5zj56VC+qqCg==

mybatis.type-handlers-package=com.rith.group1_spring_mini_project001.util

rustfs.url=http://localhost:9000
rustfs.access.name=xoD1zxOxOcuKo7jjjywU
rustfs.access.secret=xoD1zxOxOcuKo7jjjywU
rustfs.bucket.name=file-upload