spring.application.name=GROUP1_SPRING_MINI_PROJECT001
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_mini
spring.datasource.username=phal
spring.datasource.password=phal
